In [1]:
import numpy as np

In [2]:
array1 = np.array([2,3,5,7,11,13,17,19,23,29,31])

In [3]:
array1.shape

(11,)

In [4]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [5]:
array1 % 2 == 0

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [9]:
booleans = np.array([ True, False, False, False, False, False, False, False, False,
       False, False])
booleans

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [7]:
np.where(booleans)

(array([0], dtype=int64),)

In [13]:
array1 > 4
print(array1,array1>4)

[ 2  3  5  7 11 13 17 19 23 29 31] [False False  True  True  True  True  True  True  True  True  True]


In [11]:
np.where(array1>4)

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [17]:
print(array1,array1.shape)
filter = np.where(array1 > 4) #여기서where은 어디?index위치를return
print(filter)

[ 2  3  5  7 11 13 17 19 23 29 31] (11,)
(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)


In [20]:
print(filter,type(filter))
print(array1[filter],type(array1[filter]))
array1[filter]

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),) <class 'tuple'>
[ 5  7 11 13 17 19 23 29 31] <class 'numpy.ndarray'>


array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])