엔화 리스트와 달러 리스트 둘을 모두 한국원으로 바꾼 다음 2개의 원화 numpy.array를 하나로 합친다. 


In [2]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

revenue_in_dollar = [
    1200, 1600, 1400, 1300, 
    2100, 1400, 1500, 2100, 
    1500, 1500, 2300, 2100, 
    2800, 2600, 1700, 1400, 
    2100, 2300, 1600, 1800, 
    2200, 2400, 2100, 2800, 
    1900, 2100, 1800, 2200, 
    2100, 1600, 1800
]

# 코드를 작성하세요.

# 정답 출력
# won_array

In [4]:
# 첫째. numpy 모듈의 배열로 형변환과 동시에 엔화->원화로 바꿈.
revenue_yen_2_won = np.array(revenue_in_yen) * 10.08

In [8]:
revenue_yen_2_won

array([3024000., 3427200., 3225600., 3628800., 4435200., 1411200.,
       1814400., 3427200., 3326400., 2923200., 2822400., 3830400.,
       1713600., 1411200., 2318400., 3931200., 4032000., 3528000.,
       3830400., 1512000., 1108800., 2419200., 3830400., 3830400.,
       3427200., 4233600., 1512000., 1310400., 3628800., 3225600.,
       2520000.])

In [11]:
# 둘째. numpy 모듈의 배열로 형변환과 동시에 달러->원화로 바꿈.
revenue_dol_2_won = np.array(revenue_in_dollar) * 1138

In [12]:
revenue_dol_2_won

array([1365600, 1820800, 1593200, 1479400, 2389800, 1593200, 1707000,
       2389800, 1707000, 1707000, 2617400, 2389800, 3186400, 2958800,
       1934600, 1593200, 2389800, 2617400, 1820800, 2048400, 2503600,
       2731200, 2389800, 3186400, 2162200, 2389800, 2048400, 2503600,
       2389800, 1820800, 2048400])

In [13]:
total_rev_in_won = revenue_yen_2_won + revenue_dol_2_won

In [14]:
total_rev_in_won

array([31847520., 36366976., 34107248., 38057704., 47096616., 15818096.,
       19996152., 36935976., 35237112., 31172856., 31067192., 41000232.,
       20459488., 17183696., 25304072., 41219696., 43032360., 38179640.,
       40431232., 17289360., 13680304., 27116736., 41000232., 41796832.,
       36708376., 45064488., 17289360., 15712432., 38968104., 34334848.,
       27450000.])