### 파이썬 리스트를 통해 생성 
numpy 모듈의 array 메소드에 파라미터로 파이썬 리스트를 넘겨주면 np array가 리턴됨

In [2]:
import numpy

In [3]:
array1 = numpy.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])
    
print(array1)

[ 2  3  5  7 11 13 17 19 23 29 31]


## 균일한 값으로 생성
np 모듈의 full 메소드를 사용하면, 모든값이 같은 np array를 생성할 수 있다. 

In [5]:
array1 = numpy.full(6,7) # 6개의 배열을 만들거고 그 값들은 모두 7! 
print(array1)

[7 7 7 7 7 7]


In [6]:
# 방법 1. full메소드로 모든 값이 0인 배열 만들기 
# 방법 2. 다른 방법으로 만들기 

array1 = numpy.full(6,0)
array2 = numpy.zeros(6,dtype=int)
print(array1)
print()
print(array2)


[0 0 0 0 0 0]

[0 0 0 0 0 0]


In [7]:
# 방법 1. full메소드로 모든 값이 1인 배열 만들기 
# 방법 2. 다른 방법으로 만들기
array1 = numpy.full(6,1)
array2 = numpy.ones(6,dtype=int)
print(array1)
print()
print(array2)

[1 1 1 1 1 1]

[1 1 1 1 1 1]


## 랜덤한 값들로 생성
어쩔 때는 임의의 값들로 배열을 생성시키고 싶습니다. 그럴 때는 numpy의 random 모듈의 random함수를 사용하면 됩니다. 

numpy 모듈 안에 random이라는 모듈이 있고, 그 안에 또 random이라는 함수가 있는겁니다. 

In [4]:
array1 = numpy.random.random(6)
array2 = numpy.random.random(6)
print(array1)
print()
print(array2)
# 기본 소수점 8자리의 랜덤값 6개가 생성됨.

[0.99596206 0.05917362 0.92899572 0.74075511 0.27735384 0.83937115]

[0.57495503 0.30557142 0.54947754 0.86603118 0.50239424 0.05394548]


## 연속된 값들이 담긴 numpy array 생성
numpy 모듈의 arrange함수를 사용하면 연속된 값들이 담겨있는 numpy array를 생성 할 수 있음. 

arange 함수는 파이썬의 기본 함수인 range와 비슷한 원리임. 파라미터가 1개인 경우, 2개인경우, 3개인 경우 모두 살펴 봅시다. 
            
            
### 파라미터가 1개 
arange(m)을 하면 0부터 m-1까지의 값들이 담긴 numpy array가 리턴됩니다.

In [11]:
array1 = numpy.arange(6)
print(array1)

[0 1 2 3 4 5]


### 파라미터가 2개  

In [12]:
array1 = numpy.arange(3,17,3)
print(array1)

[ 3  6  9 12 15]
