In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,10,20,30,0.1,0.2])

In [4]:
# 자동으로 tuple로 잡혀서 처리 한다. 
# argmin은 최소값의 인덱스 위치를 보여준다.
np.min(a), np.argmin(a)

In [7]:
# argmin은 최소값의 인덱스 위치를 보여준다
np.max(a), np.argmax(a)

(30.0, 5)

In [11]:
a.shape,np.where(a<1)
# 요소값의 수는 총 8개이고
# 1보다 작은 요소 값의 인덱스 위치는 6,7해당.(index)

((8,), (array([6, 7], dtype=int64),))

In [15]:
a[np.where(a<1)]

array([0.1, 0.2])

In [20]:
np.where(a>=10, 0, a)
# 10보다 크거나 같은 값을 찾아서, 0으로 바꾸고, 아닌것은 그대로 두라는 조건문도 가능.  파이썬의 for문보다 빠름. 

# 즉 where메소드의 첫번째, 파라미터는 조건문이고
#                  두번째, True일 때 그걸로 변환시킴.
#                  세번째, False일 때 a의 상태로 두는 조건 
# 여기서 a는 배열 상태 그대로 둔다는말. 변경 시키지말고 그대로 둬~!

array([1. , 2. , 3. , 0. , 0. , 0. , 0.1, 0.2])

In [25]:
np.where(a>=10, a*0.1, a)

array([1. , 2. , 3. , 1. , 2. , 3. , 0.1, 0.2])